=== tao-forge/package-tao/tao/doc/structures.dtd
<!-- Root Tag -->
<!ELEMENT structures  (( structure )* , (toolbar)* ,(entrypoint)*) >
	<!ELEMENT structure  ( (description)? ,sections )>
	
		<!-- The id of the structure -->
		<!ATTLIST structure id ID #REQUIRED>
		<!-- The name of the structure -->
		<!ATTLIST structure name CDATA #REQUIRED>
		<!-- The level of that structure regarding the others (to order them)  -->
		<!ATTLIST structure level CDATA #REQUIRED>
		<!-- The id of the structure -->
		<!ATTLIST structure visible CDATA #REQUIRED>
	
		<!ELEMENT description (#PCDATA)>
		
		<!-- sub division, each section of the extension will be displayed in a separated tab -->
		<!ELEMENT sections  ( section )*>
			<!ELEMENT section  ( trees | actions )*>
				<!-- identifier of the section -->
				<!ATTLIST section id CDATA #REQUIRED>
				<!-- displayed name of the section -->
				<!ATTLIST section name CDATA #REQUIRED>
				<!-- The URL of the action to load -->
				<!ATTLIST section url CDATA #REQUIRED>
	
				<!-- The list of trees to load in the section panel -->
				<!ELEMENT trees  ( tree )*>
					<!ELEMENT tree  EMPTY>
					<!-- the name of the tree  -->
					<!ATTLIST tree name CDATA #REQUIRED>
					<!-- the URL to populate the tree with (must return JSON data)  -->
					<!ATTLIST tree dataUrl CDATA #REQUIRED>
					<!-- the URL to execute contextual actions from the tree -->
					<!ATTLIST tree className CDATA #IMPLIED>
					<!-- the name of the main class that resources are instances of in the tree -->
					<!ATTLIST tree 
						editClassUrl CDATA #IMPLIED
						editInstanceUrl CDATA #IMPLIED
						addInstanceUrl CDATA #IMPLIED
						addSubClassUrl CDATA #IMPLIED
						deleteUrl CDATA #IMPLIED
						duplicateUrl CDATA #IMPLIED
						moveInstanceUrl CDATA #IMPLIED
					>
	
				<!-- The list of contextual actions to load in the section panel -->
				<!ELEMENT actions  ( action )*>
					<!ELEMENT action  EMPTY>
					<!-- Name of the action -->
					<!ATTLIST action name CDATA #REQUIRED>
					<!-- A javascript method to run instead of loading directly the URL -->
					<!ATTLIST action js CDATA #IMPLIED>
					<!-- The URL of the action -->
					<!ATTLIST action url CDATA #REQUIRED>
					<!-- The context of the action: (class|instance|resource|*) -->
					<!ATTLIST action context CDATA #REQUIRED>
					<!-- Reload the complete page if true -->
					<!ATTLIST action reload CDATA #IMPLIED>

	<!ELEMENT entrypoint  ( description, (replace)* )>
		<!ATTLIST entrypoint id ID #REQUIRED>
		<!ATTLIST entrypoint title CDATA #REQUIRED>
		<!ATTLIST entrypoint label CDATA #REQUIRED>
		<!ATTLIST entrypoint url CDATA #REQUIRED>

		<!ELEMENT replace EMPTY>
		
			<!ATTLIST replace id CDATA #REQUIRED>
			
	<!ELEMENT toolbar  ( (toolbaraction)* )>
		<!-- displayed name of the section -->
		<!ATTLIST toolbaraction id CDATA #REQUIRED>
		<!ATTLIST toolbaraction icon CDATA #REQUIRED>
		<!ATTLIST toolbaraction level CDATA #REQUIRED>
		<!ATTLIST toolbaraction title CDATA #REQUIRED>
		<!ATTLIST toolbaraction js CDATA #IMPLIED>
		<!ATTLIST toolbaraction structure CDATA #IMPLIED>

=== tao-forge/package-tao/taoDelivery/actions/structures.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE extension SYSTEM "../../tao/doc/structures.dtd">
<structures>
	<structure id="delivery" name="Deliveries" level="4" visible="true">
		<description>Prepare, publish deliveries sessions.</description>
		<sections>
			<section id="manage_deliveries" name="Manage deliveries" url="/taoDelivery/Delivery/index">
				<trees>
					<tree name="Deliveries library"
						className="Delivery"
						dataUrl="/taoDelivery/Delivery/getDeliveries"
						editClassUrl="/taoDelivery/Delivery/editDeliveryClass"
						editInstanceUrl="/taoDelivery/Delivery/editDelivery"
						addInstanceUrl="/taoDelivery/Delivery/addDelivery"
						addSubClassUrl="/taoDelivery/Delivery/addDeliveryClass"
						deleteUrl="/taoDelivery/Delivery/delete"
						duplicateUrl="/taoDelivery/Delivery/cloneDelivery"
						moveInstanceUrl="/taoDelivery/Delivery/moveInstance"
					/>
				</trees>
				<actions>
					<action name="search" url="/taoDelivery/Delivery/search" context="*" />
					<action name="new class" js="generisActions.subClass" url="/taoDelivery/Delivery/addDeliveryClass" context="class" />
					<action name="new delivery" js="generisActions.instanciate" url="/taoDelivery/Delivery/addDelivery" context="class" />
					<action name="delete" js="generisActions.removeNode" url="/taoDelivery/Delivery/delete" context="resource" />
					<action name="duplicate" js="generisActions.duplicateNode" url="/taoDelivery/Delivery/cloneDelivery" context="instance" />
					<action name="move" js="generisActions.moveNode" url="" context="instance" />
					<action name="export" url="/tao/Export/index"  context="*" />
					<action name="import" url="/tao/Import/index"  context="class" />
					<action name="LTI export" url="/ltiDeliveryProvider/DeliveryLinks/index" context="instance" />
				</actions>
			</section>

		<section id="manage_resultservers" name="Manage result servers" url="/taoDelivery/ResultServer/index">
				<trees>
					<tree name="Result Servers library"
						className="Result Server"
						dataUrl="/taoDelivery/ResultServer/getResultServers"
						editClassUrl="/taoDelivery/ResultServer/editResultServerClass"
						editInstanceUrl="/taoDelivery/ResultServer/editResultServer"
						addInstanceUrl="/taoDelivery/ResultServer/addResultServer"
						addSubClassUrl="/taoDelivery/ResultServer/addResultServerClass"
						deleteUrl="/taoDelivery/ResultServer/delete"
						duplicateUrl="/taoDelivery/ResultServer/cloneInstance"
						moveInstanceUrl="/taoDelivery/ResultServer/moveInstance"
					/>
				</trees>
				<actions>
					<action name="search" url="/taoDelivery/ResultServer/search" context="*" />
					<action name="new class" js="generisActions.subClass" url="/taoDelivery/ResultServer/addResultServerClass" context="class" />
					<action name="new result server" js="generisActions.instanciate" url="/taoDelivery/ResultServer/addResultServer" context="class" />
					<action name="delete" js="generisActions.removeNode" url="/taoDelivery/ResultServer/delete" context="resource" />
					<action name="duplicate" js="generisActions.duplicateNode" url="/taoDelivery/ResultServer/cloneInstance" context="instance" />
					<action name="move" js="generisActions.moveNode" url="" context="instance" />
					<action name="export" url="/tao/Export/index"  context="*" />
					<action name="import" url="/tao/Import/index"  context="class" />
				</actions>
			</section>

		</sections>
	</structure>
</structures>

=== tao-forge/package-tao/tao/test/samples/structures/tao/structures.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE extension SYSTEM "../doc/structures.dtd">
<structures>
	<structure id="users" name="Users" url="/tao/Users/index" level="8" visible="false">
		<description />
		<sections>
			<section id="list_users" name="Manage users" url="/tao/Users/index" />
			<section id="add_user" name="Add a user" url="/tao/Users/add" />
			<section id="edit_user" name="Edit a user" url="/tao/Users/edit" />
			<section id="manage_rolesrights" name="Manages Roles Rights" url="/tao/Roles/index" />
		</sections>
	</structure>
</structures>

=== tao-forge/package-tao/tao/actions/structures.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE extension SYSTEM "../doc/structures.dtd">
<structures>
	<structure id="users" name="Users" level="8" visible="false">
		<description />
		<sections>
			<section id="list_users" name="Manage users" url="/tao/Users/index" />
			<section id="add_user" name="Add a user" url="/tao/Users/add" />
			<section id="edit_user" name="Edit a user" url="/tao/Users/edit" />
			<section id="manage_acl" name="Manage ACL" url="/tao/Acl/index" />
		</sections>
	</structure>
	<structure id="settings" name="Settings" level="11" visible="false">
		<description />
		<sections>
			<section id="settings_my_settings" name="My settings" url="/tao/UserSettings/properties" />
			<section id="settings_my_password" name="Change password" url="/tao/UserSettings/password" />
			<section id="settings_optimisation" name="TAO optimizer" url="/tao/Settings/index" />
			<section id="settings_versioning" name="Revision control" url="/tao/SettingsVersioning/index">
				<trees>
					<tree name="Repositories"
						className="Repository"
						dataUrl="/tao/SettingsVersioning/getOntologyData"
						editClassUrl="/tao/SettingsVersioning/index"
						editInstanceUrl="/tao/SettingsVersioning/editRepository"
						addInstanceUrl="/tao/SettingsVersioning/addInstance"
						deleteUrl="/tao/SettingsVersioning/delete"
					/>
				</trees>
				<actions>
					<action name="add repository" js="generisActions.instanciate" url="/tao/SettingsVersioning/addInstance" context="class" />
					<action name="remove repository" js="generisActions.removeNode" url="/tao/SettingsVersioning/delete" context="instance" />
				</actions>
			</section>
			<section id="settings_ext_mng" name="Extensions manager" url="/tao/ExtensionsManager/index" />
		</sections>
	</structure>
</structures>

=== tao-forge/package-tao/taoLti/actions/structures.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE extension SYSTEM "../../tao/doc/structures.dtd">
<structures>
	<structure id="settings" name="Settings" level="11" visible="false">
		<description />
		<sections>
			<section id="settings_oauth_mng" name="LTI Consumers" url="/taoLti/ConsumerAdmin/index">
				<trees>
					<tree name="LTI Consumers"
						className="LTI Consumers"
						dataUrl="/taoLti/ConsumerAdmin/getOntologyData"
						editInstanceUrl="/taoLti/ConsumerAdmin/editInstance"
						addInstanceUrl="/taoLti/ConsumerAdmin/addInstance"
						deleteUrl="/taoLti/ConsumerAdmin/delete"
					/>
				</trees>
				<actions>
					<action name="add Consumer" url="/taoLti/ConsumerAdmin/addInstanceForm" context="class" />
					<action name="delete" js="removeNode" url="/taoLti/ConsumerAdmin/delete" context="instance" />
					<action name="export" url="/tao/Export/index"  context="resource" />
					<action name="import" url="/tao/Import/index"  context="class" />					
				</actions>
			</section>
		</sections>
	</structure>
</structures>

=== tao-forge/package-tao/tao/test/samples/structures/items/structures.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE extension SYSTEM "../../tao/doc/structures.dtd">
<structures>
	<structure id="items" name="Items" url="/taoItems/Items/index" level="0" visible="true">
		<description>Create and design items and exercises.</description>
		<sections>
			<section id="manage_items" name="Manage items" url="/taoItems/Items/index">
				<trees>
					<tree name="Items library" 
						dataUrl="/taoItems/Items/getOntologyData" 
						editClassUrl="/taoItems/Items/editItemClass"
						editInstanceUrl="/taoItems/Items/editItem"
						addInstanceUrl="/taoItems/Items/addInstance"
						addSubClassUrl="/taoItems/Items/addItemClass"
						deleteUrl="/taoItems/Items/delete"
						duplicateUrl="/taoItems/Items/cloneInstance"
						moveInstanceUrl="/taoItems/Items/moveInstance"
					/>
				</trees>
				<actions>
					<action name="search" url="/taoItems/Items/search" context="*" />
					<action name="new class" js="GenerisAction.subClass" url="/taoItems/Items/addItemClass" context="class" />
					<action name="new item" js="GenerisAction.instanciate" url="/taoItems/Items/addInstance" context="class" />
					<action name="delete" js="GenerisAction.removeNode" url="/taoItems/Items/delete" context="resource" />
					<action name="duplicate" js="GenerisAction.duplicateNode" url="/taoItems/Items/cloneInstance" context="instance" />
					<action name="move" js="GenerisAction.moveNode" url="" context="instance" />
					<action name="preview" js="GenerisAction.fullScreen" url="/taoItems/Items/fullScreenPreview" context="instance" />
					<action name="lists"  url="/tao/Lists/index"  context="*" />
					<action name="meta data" js="GenerisAction.loadMetaData" url="/taoItems/Items/getMetaData"  context="instance" />
					<action name="create table" url="/taoResults/LegacyResults/createTable"  context="class" />
					<action name="export" url="/taoItems/ItemExport/index"  context="*" /> 
					<action name="import" url="/taoItems/ItemImport/index"  context="class" /> 
				</actions>
			</section>
			<section id="items_authoring" name="Authoring" url="/taoItems/Items/authoring" />
			<section id="items_preview" name="Full preview" url="/taoItems/Items/preview" />
		</sections>
	</structure>
</structures>

=== tao-forge/package-tao/taoResultServer/actions/structures.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE extension SYSTEM "../../tao/doc/structures.dtd">
<structures>
    <structure id="resultserver" name="Result Server" visible="true">
		<description>Manage Result Servers</description>
    <sections>
    <section id="manage_resultservers" name="Manage result servers" url="/taoResultServer/ResultServer/index">
				<trees>
					<tree name="Result Servers library"
						className="Result Server"
						dataUrl="/taoResultServer/ResultServer/getResultServers"
						editClassUrl="/taoResultServer/ResultServer/editResultServerClass"
						editInstanceUrl="/taoResultServer/ResultServer/editResultServer"
						addInstanceUrl="/taoResultServer/ResultServer/addResultServer"
						addSubClassUrl="/taoResultServer/ResultServer/addResultServerClass"
						deleteUrl="/taoResultServer/ResultServer/delete"
						duplicateUrl="/taoResultServer/ResultServer/cloneInstance"
						moveInstanceUrl="/taoResultServer/ResultServer/moveInstance"
					/>
				</trees>
				<actions>
					<action name="search" url="/taoResultServer/ResultServer/search" context="*" />
					<action name="new class" js="generisActions.subClass" url="/taoResultServer/ResultServer/addResultServerClass" context="class" />
					<action name="new result server" js="generisActions.instanciate" url="/taoResultServer/ResultServer/addResultServer" context="class" />
					<action name="delete" js="generisActions.removeNode" url="/taoResultServer/ResultServer/delete" context="resource" />
					<action name="duplicate" js="generisActions.duplicateNode" url="/taoResultServer/ResultServer/cloneInstance" context="instance" />
					<action name="move" js="generisActions.moveNode" url="" context="instance" />
					<action name="export" url="/tao/Export/index"  context="*" />
					<action name="import" url="/tao/Import/index"  context="class" />
				</actions>
			</section>
     </sections>
    </structure>
</structures>
